# Uncomment the next line to define a global platform for your project
 platform :ios, '12.1'

target 'vcarUser' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
  pod 'Firebase/Core', '~> 6.3.0'
  pod 'Firebase/Messaging', '~> 6.3.0'
  pod 'FacebookSDK'
  pod 'FBSDKCoreKit', '~>4.40.0'
pod 'FBSDKLoginKit', '~>4.40.0'
pod 'FBSDKShareKit', '~>4.40.0'
pod 'Bolts'
pod 'AccountKit'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'Google-Maps-iOS-Utils'

end

